name: causal-tns
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytest
  - ruff
  - pip:
      - torch==2.14.0
      - tensorkrowch==1.1.6
      - numpy
      - matplotlib
      - scipy
      - -e .
